version: "3.9"

services:
  web:
    build: .
    command: sh -c "cd app && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=white_snake
      - POSTGRES_PASSWORD=white_snake
      - POSTGRES_DB=white_snake

volumes:
  postgres_data: