# Generated by Django 3.0 on 2021-10-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="partners",
            field=models.ManyToManyField(
                related_name="_company_partners_+", to="api.Company"
            ),
        ),
    ]
